### Note: This files are created to show the errors in the staticcode analysis phase during KubeLinter and Kubesec scan.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    checkov.io/skip1: CKV2_K8S_6
    checkov.io/skip2: CKV_K8S_8
    checkov.io/skip3: CKV_K8S_9
    checkov.io/skip4: CKV_K8S_10
    checkov.io/skip5: CKV_K8S_11
    checkov.io/skip6: CKV_K8S_12
    checkov.io/skip7: CKV_K8S_13
    checkov.io/skip8: CKV_K8S_15
    checkov.io/skip9: CKV_K8S_16
    checkov.io/skip10: CKV_K8S_20
    checkov.io/skip11: CKV_K8S_21
    checkov.io/skip12: CKV_K8S_22
    checkov.io/skip13: CKV_K8S_23
    checkov.io/skip14: CKV_K8S_28
    checkov.io/skip15: CKV_K8S_29
    checkov.io/skip16: CKV_K8S_30
    checkov.io/skip17: CKV_K8S_31
    checkov.io/skip18: CKV_K8S_37
    checkov.io/skip19: CKV_K8S_38
    checkov.io/skip20: CKV_K8S_40
    checkov.io/skip21: CKV_K8S_43
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
